import { describe, expect, it } from "vitest";
import { firstPrinciplesBundleSchema } from "../first-principles/types";
import { researchClaimsSchema } from "../research/live-types";
import { vocCorpusSchema } from "../voc/types";
import { consumerDecisionChainArtifactSchema } from "./types";
import { validateConsumerDecisionChain } from "./validation";

const runId = "research-run-psychology-test-us";
const generatedAt = "2026-08-03T08:00:00.000Z";

const corpus = vocCorpusSchema.parse({
  schema_version: "1.0",
  run_id: runId,
  product: "Test leggings",
  market: "US",
  generated_at: generatedAt,
  methodology: "VOICE_OF_CUSTOMER_RESEARCH_STANDARD_V1",
  denominator_definition: "All valid observations in the bounded test corpus.",
  source_pages: [{
    source_id: "SRC-001",
    url: "https://example.com/reviews",
    title: "Test reviews",
    platform: "Example",
    source_family: "community",
    captured_at: generatedAt,
    access_status: "accessible",
    snapshot_path: "source_snapshots/SRC-001.md",
    product_scope: "competitor_product",
    access_notes: "Public test page",
  }],
  observations: [
    {
      observation_id: "VOC-001",
      research_run_id: runId,
      source_id: "SRC-001",
      snapshot_path: "source_snapshots/SRC-001.md",
      platform: "Example",
      source_family: "community",
      page_url: "https://example.com/reviews",
      page_title: "Test reviews",
      captured_at: generatedAt,
      observation_type: "pain",
      sentiment: "negative",
      theme: "visible styling",
      paraphrase: "A wearer felt conspicuous when the seam became highly visible in public.",
      quote_excerpt: null,
      product_scope: "competitor_product",
      variant_match: "not_applicable",
      firsthand_status: "explicit",
      rating: null,
      privacy_reviewed: true,
      copyright_reviewed: true,
    },
    {
      observation_id: "VOC-002",
      research_run_id: runId,
      source_id: "SRC-001",
      snapshot_path: "source_snapshots/SRC-001.md",
      platform: "Example",
      source_family: "community",
      page_url: "https://example.com/reviews",
      page_title: "Test reviews",
      captured_at: generatedAt,
      observation_type: "desired_outcome",
      sentiment: "positive",
      theme: "subtle contour",
      paraphrase: "The wearer preferred a flattering but less conspicuous contour.",
      quote_excerpt: null,
      product_scope: "competitor_product",
      variant_match: "not_applicable",
      firsthand_status: "explicit",
      rating: null,
      privacy_reviewed: true,
      copyright_reviewed: true,
    },
    {
      observation_id: "VOC-003",
      research_run_id: runId,
      source_id: "SRC-001",
      snapshot_path: "source_snapshots/SRC-001.md",
      platform: "Example",
      source_family: "community",
      page_url: "https://example.com/reviews",
      page_title: "Test reviews",
      captured_at: generatedAt,
      observation_type: "counterevidence",
      sentiment: "positive",
      theme: "individual preference",
      paraphrase: "Another wearer liked the visible construction and reported no discomfort.",
      quote_excerpt: null,
      product_scope: "competitor_product",
      variant_match: "not_applicable",
      firsthand_status: "explicit",
      rating: null,
      privacy_reviewed: true,
      copyright_reviewed: true,
    },
  ],
  amazon_comment_level_evidence: false,
  limitations: ["Bounded test corpus"],
});

const firstPrinciples = firstPrinciplesBundleSchema.parse({
  schema_version: "1.0",
  run_id: runId,
  product: "Test leggings",
  market: "US",
  generated_at: generatedAt,
  methodology: "SACL",
  resources: {
    budget: null,
    available_time: null,
    team_size: null,
    current_supplier_resources: [],
    current_channel_assets: [],
    current_content_assets: [],
    acceptable_moq: null,
    target_margin: null,
    unacceptable_risks: [],
    preferred_business_model: null,
    validation_goal: null,
  },
  problem_reframe: {
    surface_product: "Test leggings",
    conventional_question: "Which leggings should be sold?",
    reframed_problem: "How can a wearer get a flattering but restrained silhouette?",
    target_user: "Activewear buyer",
    triggering_scenario: "Public movement",
    desired_outcome: "Subtle contour",
    willingness_to_pay_reason: "More confidence with less adjustment",
    supporting_claim_ids: ["CLM-001"],
    assumptions: ["Preference may vary"],
  },
  fact_hypothesis_unknown: {
    facts: [{
      id: "FACT-001",
      statement: "Visible styling is polarizing.",
      classification: "fact",
      scope: "user_need",
      supporting_claim_ids: ["CLM-001"],
      confidence: "medium",
      rationale: "Current-run observation",
      validation_required: false,
    }],
    hypotheses: [{
      id: "HYP-001",
      statement: "Subtle styling may be preferred.",
      classification: "hypothesis",
      scope: "user_need",
      supporting_claim_ids: ["CLM-001"],
      confidence: "medium",
      rationale: "Needs concept testing",
      validation_required: true,
    }],
    unknowns: [{
      id: "UNK-001",
      statement: "Preferred proof format is unknown.",
      classification: "unknown",
      scope: "user_need",
      supporting_claim_ids: [],
      confidence: "low",
      rationale: "No proof-format test",
      validation_required: true,
    }],
  },
  demand_atoms: [{
    id: "DEM-001",
    user_segment: "Activewear buyer",
    scenario: "Movement in public",
    trigger: "Visible seam styling",
    pain_or_job: "Avoid unwanted attention",
    desired_outcome: "Natural contour",
    current_alternative: "Non-scrunch leggings",
    current_alternative_gap: "Less contour",
    importance: "medium",
    evidence_status: "directional",
    supporting_claim_ids: ["CLM-001"],
    confidence: "medium",
  }],
  supply_atoms: [{
    id: "SUP-001",
    category: "structure",
    name: "Hidden seam",
    description: "A less visible contour construction",
    independently_sourceable: true,
    cost_visibility: "unknown",
    customization_level: "light_customization",
    supplier_or_source_signal_claim_ids: ["CLM-001"],
    target_sku_verified: false,
    confidence: "low",
  }],
  constraints: {
    hard: [{
      id: "CON-001",
      type: "hard",
      statement: "Do not make unsupported health claims.",
      impact: "Marketing restriction",
      design_response: "Use visual and comfort tests",
      supporting_claim_ids: ["CLM-001"],
      confidence: "medium",
    }],
    soft: [],
    pseudo: [{
      id: "CON-002",
      type: "pseudo",
      statement: "Every wearer wants visible scrunch.",
      impact: "Would overgeneralize preference",
      design_response: "Test preference segments",
      supporting_claim_ids: ["CLM-001"],
      confidence: "medium",
    }],
  },
  opportunity_hypotheses: ["OPP-001", "OPP-002"].map((id) => ({
    id,
    title: `Opportunity ${id}`,
    target_demand_atom_ids: ["DEM-001"],
    supply_atom_ids: ["SUP-001"],
    product_or_offer_concept: "A restrained contour legging",
    target_customer: "Activewear buyer",
    target_scenario: "Movement in public",
    core_value_proposition: "Flattering shape without conspicuous styling",
    differentiation: ["Hidden contour"],
    explicit_non_goals: ["No health claims"],
    required_claim_ids: ["CLM-001"],
    unsupported_assumptions: ["Preference size"],
    primary_risks: ["Fit varies"],
    feasibility: "medium",
    desirability: "medium",
    evidence_strength: "medium",
    estimated_test_cost_level: "low",
    scores: Object.fromEntries([
      "demand_fit", "evidence_strength", "differentiation", "supply_feasibility",
      "constraint_fit", "validation_cost", "monetization_potential", "risk_exposure",
    ].map((key) => [key, { score: 60, status: "scored", rationale: "Test score", claim_ids: ["CLM-001"] }])),
    score: 60,
    score_rationale: "A bounded test opportunity",
  })),
  recommended_opportunity_id: "OPP-001",
  recommendation_rationale: "It best matches the observed preference tension.",
  alternatives_not_recommended: [{ opportunity_id: "OPP-002", reason: "Lower priority" }],
  validation_plan: [{
    id: "VAL-001",
    opportunity_id: "OPP-001",
    critical_assumption: "Users recognize the restrained difference",
    test_type: "concept_test",
    target_participant_or_source: "Activewear buyers",
    method: "Blind concept comparison",
    sample_size_or_scope: "10 participants",
    budget_cap: "USD 100",
    duration_days: 3,
    metric: "Preference",
    pass_threshold: "60% prefer restrained",
    fail_threshold: "Below 40%",
    stop_condition: "No recognized difference",
    next_action_if_pass: "Source samples",
    next_action_if_fail: "Revise concept",
  }],
  decision_summary: {
    first_principles_recommendation: "Test the restrained direction",
    product_selection_decision: "HOLD_RESEARCH",
    formal_sku_decision: "HOLD_SUPPLY",
    listing_allowed: false,
    ad_test_allowed: false,
    evidence_strength: "medium",
    entry_conditions: ["Validate preference"],
    boundary_rationale: "The target product is untested.",
  },
});

const claims = researchClaimsSchema.parse([{
  id: "CLM-001",
  sourceId: "SRC-001",
  statement: "Visible styling is polarizing in the sampled discussion.",
  evidence: "Current-run community observations include both discomfort and preference.",
  confidence: "Medium",
  category: "customer",
  targetScope: "market",
}]);

const validArtifact = () => consumerDecisionChainArtifactSchema.parse({
  schema_version: "1.0",
  run_id: runId,
  product: "Test leggings",
  market: "US",
  generated_at: generatedAt,
  methodology: "CONSUMER_PSYCHOLOGY_DECISION_CHAIN_V1",
  source_artifacts: {
    voc_corpus: "voc-corpus.json",
    first_principles_bundle: "first-principles-bundle.json",
    claims: "claims.json",
  },
  stages: [
    {
      id: "PSY-001",
      stage: "situational_trigger",
      mechanism: "situational_trigger",
      scope: "category_user",
      basis: "direct_user_expression",
      conclusion: "Visible seam styling becomes salient during movement in public settings.",
      evidence_status: "supported",
      supporting_observation_ids: ["VOC-001"],
      supporting_claim_ids: ["CLM-001"],
      supporting_demand_atom_ids: ["DEM-001"],
      counterevidence_observation_ids: ["VOC-003"],
      counterevidence_claim_ids: [],
      unknowns: ["Frequency across the market is unknown"],
      validation_needed: [],
      claim_boundary: "This describes the sampled category experience only.",
    },
    {
      id: "PSY-002",
      stage: "tension_activation",
      mechanism: "loss_aversion",
      scope: "category_user",
      basis: "direct_user_expression",
      conclusion: "Some wearers want to avoid feeling conspicuous or distracted by the construction.",
      evidence_status: "supported",
      supporting_observation_ids: ["VOC-001"],
      supporting_claim_ids: ["CLM-001"],
      supporting_demand_atom_ids: ["DEM-001"],
      counterevidence_observation_ids: ["VOC-003"],
      counterevidence_claim_ids: [],
      unknowns: ["The strength of the tension varies"],
      validation_needed: [],
      claim_boundary: "Do not manufacture shame or universalize the concern.",
    },
    {
      id: "PSY-003",
      stage: "identity_projection",
      mechanism: "identity_projection",
      scope: "category_user",
      basis: "direct_user_expression",
      conclusion: "The desired presentation is flattering and confident without conspicuous contouring.",
      evidence_status: "supported",
      supporting_observation_ids: ["VOC-002"],
      supporting_claim_ids: ["CLM-001"],
      supporting_demand_atom_ids: ["DEM-001"],
      counterevidence_observation_ids: ["VOC-003"],
      counterevidence_claim_ids: [],
      unknowns: ["Preference segments need sizing"],
      validation_needed: [],
      claim_boundary: "This is a preference segment, not a universal identity.",
    },
    {
      id: "PSY-004",
      stage: "outcome_imagination",
      mechanism: "cognitive_fluency",
      scope: "proposed_offer",
      basis: "evidence_synthesis",
      conclusion: "A restrained contour is easier to understand when shown as a visible styling difference.",
      evidence_status: "directional",
      supporting_observation_ids: ["VOC-002"],
      supporting_claim_ids: ["CLM-001"],
      supporting_demand_atom_ids: ["DEM-001"],
      counterevidence_observation_ids: ["VOC-003"],
      counterevidence_claim_ids: [],
      unknowns: ["The target sample has not demonstrated the difference"],
      validation_needed: ["Run a same-light blind comparison"],
      claim_boundary: "Describe a concept until a target sample is tested.",
    },
    {
      id: "PSY-005",
      stage: "belief_formation",
      mechanism: "belief_formation",
      scope: "proposed_offer",
      basis: "model_hypothesis",
      conclusion: "Same-light comparisons and body-shape examples may make the promise more credible.",
      evidence_status: "hypothesis",
      supporting_observation_ids: ["VOC-001", "VOC-002"],
      supporting_claim_ids: ["CLM-001"],
      supporting_demand_atom_ids: ["DEM-001"],
      counterevidence_observation_ids: ["VOC-003"],
      counterevidence_claim_ids: [],
      unknowns: ["Preferred proof format is unknown"],
      validation_needed: ["Compare proof formats with target users"],
      claim_boundary: "Proof format preference is not established.",
    },
    {
      id: "PSY-006",
      stage: "risk_reduction",
      mechanism: "uncertainty_reduction",
      scope: "proposed_offer",
      basis: "model_hypothesis",
      conclusion: "Clear fit evidence and exchange terms may reduce hesitation for a polarizing construction.",
      evidence_status: "hypothesis",
      supporting_observation_ids: ["VOC-001", "VOC-003"],
      supporting_claim_ids: ["CLM-001"],
      supporting_demand_atom_ids: ["DEM-001"],
      counterevidence_observation_ids: [],
      counterevidence_claim_ids: [],
      unknowns: ["The strongest risk-reversal mechanism is unknown"],
      validation_needed: ["Test sizing proof against exchange and refund options"],
      claim_boundary: "No purchase-conversion effect has been measured.",
    },
  ],
  overall_boundary: "This chain explains a bounded decision hypothesis and does not prove target-product performance or purchase conversion.",
  ethical_boundary: {
    no_manufactured_shame: true,
    no_sensitive_trait_inference: true,
    no_unverified_health_claims: true,
  },
  decision_boundary: {
    current_product_decision_unchanged: true,
    target_sku_performance_not_proven: true,
    marketing_remains_draft_for_validation: true,
    no_automatic_listing_or_ad_approval: true,
  },
});

describe("consumer psychology decision-chain validation", () => {
  it("accepts a complete current-run six-stage chain", () => {
    const result = validateConsumerDecisionChain(validArtifact(), corpus, firstPrinciples, claims);
    expect(result.valid).toBe(true);
    expect(result.summary).toMatchObject({
      stage_count: 6,
      supported_count: 3,
      directional_count: 1,
      hypothesis_count: 2,
      mapping_error_count: 0,
    });
  });

  it("rejects evidence IDs from another run", () => {
    const artifact = validArtifact();
    artifact.stages[0].supporting_observation_ids = ["VOC-FOREIGN"];
    const result = validateConsumerDecisionChain(artifact, corpus, firstPrinciples, claims);
    expect(result.errors.map((item) => item.code)).toContain("PSYCHOLOGY_OBSERVATION_NOT_IN_CURRENT_RUN");
  });

  it("rejects a competitor observation used as target-product proof", () => {
    const artifact = validArtifact();
    artifact.stages[3].scope = "target_product";
    const result = validateConsumerDecisionChain(artifact, corpus, firstPrinciples, claims);
    expect(result.errors.map((item) => item.code)).toContain("COMPETITOR_OBSERVATION_USED_AS_TARGET_PROOF");
  });

  it("rejects unverified health language in a proposed offer", () => {
    const artifact = validArtifact();
    artifact.stages[3].conclusion = "The proposed offer can eliminate cellulite and improve circulation.";
    const result = validateConsumerDecisionChain(artifact, corpus, firstPrinciples, claims);
    expect(result.errors.map((item) => item.code)).toContain("UNVERIFIED_HEALTH_OR_PERMANENCE_CLAIM");
  });

  it("rejects a derived interpretation marked as supported", () => {
    const payload = validArtifact();
    payload.stages[4] = {
      ...payload.stages[4],
      evidence_status: "supported",
      basis: "evidence_synthesis",
    };
    expect(() => consumerDecisionChainArtifactSchema.parse(payload)).toThrow();
  });
});
