import type { DemandFieldArtifact } from "./types";

const textLabels: Record<string, string> = {
  "Proof-seeking activewear buyers": "重视实证的运动服买家",
  "Activewear buyers who use leggings for movement and want observable proof for opacity, fit, comfort, and durability before trusting product claims.": "在运动场景中穿着紧身裤，并希望在相信产品宣传前看到不透、版型、舒适度和耐久性实证的买家。",
  "Restrained-sculpt gym-to-public wearers": "偏好克制塑形的训练到日常穿着者",
  "Wearers who value a flattering activewear silhouette but reject exaggerated contouring, physical discomfort, or styling that creates unwanted attention in public settings.": "重视运动服修饰效果，但排斥夸张塑形、身体不适或在公共场景引发多余关注的穿着者。",
  "Select fit and coverage": "选择版型与遮盖能力",
  "Choose a size, color, and construction likely to remain comfortable and opaque": "选择更可能保持舒适和不透的尺码、颜色与结构",
  "Train with full movement": "完成大幅度训练动作",
  "Complete lower-body movement without exposure, discomfort, adjustment, or structural failure": "完成下肢动作时避免走光、不适、反复调整或结构失效",
  "Continue into public settings": "继续进入公共场景",
  "Move from training to daily activities with socially comfortable coverage and styling": "从训练自然过渡到日常活动，并保持合适的遮盖与外观",
  "Wash and preserve": "清洗并维持状态",
  "Maintain fabric, seams, fit, and appearance over repeated wear cycles": "在反复穿洗中维持面料、缝线、版型与外观",
  "Lower-body training under bright light": "明亮环境下的大幅度下肢训练",
  "Online fit selection without try-on": "无法试穿时在线选择版型与尺码",
  "Workout-to-public transition": "训练结束后继续进入通勤或日常场景",
  "Verifiable squat opacity": "可验证的深蹲不透表现",
  "Opacity must hold under movement, bright light, and the exact color and fabric rather than as a generic listing claim.": "不透表现必须在运动、明亮光线以及具体颜色和面料上成立，而不能只依赖笼统的商品页宣称。",
  "Restrained natural contour": "克制自然的塑形",
  "The garment should create a flattering silhouette without an exaggerated visible scrunch or physical discomfort.": "在修饰身形的同时，避免夸张可见的提臀缝和身体不适。",
  "Predictable fit and sizing": "更可预期的版型与尺码",
  "Remote buyers need more confidence that waist, hip, compression, and length will fit their proportions.": "线上买家需要更有把握地判断腰围、臀围、压缩感和裤长是否适合自己的比例。",
  "Seam and fabric durability": "缝线与面料耐久性",
  "Scrunch seams, general stitching, and fabric must survive repeated wear and ordinary care without tearing, holes, or early pilling.": "提臀缝、普通缝线和面料需要经受反复穿着与日常护理，避免开裂、破洞或过早起球。",
  "Low-friction coverage fallback": "低负担的遮盖补救方案",
  "Some wearers compensate for uncertain opacity with a separate undergarment choice.": "部分穿着者会通过额外选择内衣来补救不确定的不透表现。",
  "Activewear care and protection": "运动服洗护与保护",
  "Durability complaints suggest a possible post-use need to reduce friction, pilling, and seam stress during washing and storage.": "耐久性投诉提示，用户可能需要在清洗和收纳中降低摩擦、起球及缝线受力。",
  "Reliable squat opacity with documented proof": "有测试记录支撑的深蹲不透表现",
  "Natural sculpting with restrained seam visibility": "后缝低存在感的自然塑形",
  "Stable comfortable construction through extended wear": "长时间穿着仍稳定舒适的结构",
  "Versatile styling, stable waistband, and practical storage": "兼顾多场景、稳定腰头与实用收纳",
  "Is this a stable complementary purchase or only a workaround for poor leggings?": "这是稳定的互补购买，还是只在紧身裤表现不佳时使用的补救方案？",
  "Which failure matters most: visible lines, movement, sweat, or opacity?": "用户最在意的是内衣痕迹、移位、出汗不适还是透视？",
  "Do users attribute failures to washing, garment quality, or both?": "用户认为问题来自洗护方式、衣物质量，还是两者共同作用？",
  "Would a dedicated care system outperform ordinary mesh laundry bags?": "专用洗护系统是否明显优于普通网眼洗衣袋？",
  "Is public coverage a recurring product need or a garment-quality failure?": "公共场景遮盖是重复出现的独立需求，还是紧身裤质量问题造成的补救需求？",
  "Would users carry a dedicated layer instead of changing clothes or choosing different leggings?": "用户是否愿意携带专用遮挡层，而不是换衣服或选择另一条紧身裤？",
  "No-show training underwear": "无痕运动内裤",
  "Seamless activewear underwear": "无缝运动内裤",
  "The corpus directly records underwear as an opacity workaround in the same training-to-public task, but only one observation names the product solution.": "当前语料直接记录了在训练到公共场景任务中用内衣解决透视问题，但只有一条观察明确提到这一商品方案。",
  "The evidence does not establish recurring demand, willingness to pay, differentiation, supply feasibility, or whether better leggings remove the need.": "现有证据尚不能证明重复需求、付费意愿、差异化、供应可行性，也不能判断更好的紧身裤是否会直接消除该需求。",
  "Activewear wash-protection system": "运动服洗护保护系统",
  "Activewear laundry bag and garment-care accessories": "运动服洗衣袋与衣物护理配件",
  "Durability and pilling are recurring across community, marketplace, and brand-hosted evidence, creating a plausible post-use care job, but no current observation directly asks for a care product.": "耐久和起球问题在社区、零售平台及品牌评论中反复出现，形成了合理的使用后护理任务，但当前没有观察直接提出购买护理产品。",
  "The corpus does not distinguish manufacturing defects from care-related damage and contains no direct adjacent-product demand or willingness-to-pay evidence.": "当前语料无法区分制造缺陷和护理不当造成的损伤，也没有相邻商品的直接需求或付费意愿证据。",
  "Gym-to-street coverage layer": "健身到通勤遮挡层",
  "Lightweight activewear wrap or packable coverage layer": "轻量运动围裹层或可收纳遮挡层",
  "Unwanted attention and public opacity failures reveal a post-workout coverage job, but the current corpus does not directly mention wraps, cover-ups, or willingness to carry another layer.": "多余关注和公共场景透视问题暴露出训练后的遮挡任务，但当前语料没有直接提到围裹层、罩衫或携带额外衣物的意愿。",
  "The candidate product is a task-chain inference and may treat the symptom of poor leggings rather than a durable independent need.": "这个候选商品来自任务链推断，可能只是在补救紧身裤质量问题，而不是稳定、独立的需求。",
};

const relationshipLabels: Record<string, string> = {
  SAME_AUDIENCE: "同一人群",
  SAME_SCENARIO: "同一场景",
  SAME_JOB: "同一任务",
  ADJACENT_JOB: "相邻任务",
  COMPLEMENTARY: "互补商品",
  SUBSTITUTE: "替代商品",
  PRE_USE: "使用前",
  POST_USE: "使用后",
};

const statusLabels: Record<string, string> = {
  supported: "已有支持",
  directional: "方向性证据",
  hypothesis: "研究假设",
  prohibited: "禁止使用",
  draft_for_validation: "待验证草案",
  ready_for_use: "可使用",
  strong: "强",
  moderate: "中等",
  weak: "弱",
  uncertain: "不确定",
  RESEARCH_MORE: "需要继续研究",
  NOT_PRIORITIZED: "暂不优先",
  pre_use: "使用前",
  core_use: "核心使用",
  post_use: "使用后",
  parallel: "并行任务",
  outside_current_scope: "当前范围外",
};

export const demandFieldTextZh = (value: string): string => textLabels[value] ?? value;
export const demandRelationshipZh = (value: string): string => relationshipLabels[value] ?? value;
export const demandStatusZh = (value: string): string => statusLabels[value] ?? value;

export const demandFieldMetrics = (artifact: DemandFieldArtifact) => ({
  audiences: artifact.audience_clusters.length,
  scenarios: artifact.scenarios.length,
  taskSteps: artifact.task_chain.length,
  opportunities: artifact.adjacent_opportunities.length,
  directOpportunities: artifact.adjacent_opportunities.filter((item) => item.direct_product_evidence).length,
});
