import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const runId = "research-run-product-7f4ddc865607-us";
const root = path.join(process.cwd(), "output", "research", runId);
const at = "2026-08-13T12:00:00.000Z";

type Row = { id: string; file: string; url: string; title: string; sourceType: "market" | "competitor" | "regulation" | "other"; entity: string; notes: string; body: string };
const rows: Row[] = [
  { id:"SRC-REF-029", file:"refrigerator-filter-29.md", url:"https://www.asinsight.com/report/US/everydrop-edr1rxd1", title:"ASINSIGHT EDR1RXD1 相邻月趋势代理", sourceType:"market", entity:"EDR1RXD1 B00UXG4WR8", notes:"第三方 Amazon 估算，同一页面同一 ASIN 的相邻月代理，不是官方订单。", body:"# EDR1RXD1 相邻月趋势代理\n\n2026-07 估算月销量 90,000，环比 +1.5%，反推 2026-06 约 88,700。页面还显示近 13 个月趋势轴，但公开文本未提供每月点值。价格 $50.80；周搜索量 232，周变化 +20%。仅作方向与量级代理。\n" },
  { id:"SRC-REF-030", file:"refrigerator-filter-30.md", url:"https://www.asinsight.com/report/US/samsung-water-filter-replacement", title:"ASINSIGHT HAF-QIN 相邻月趋势代理", sourceType:"market", entity:"HAF-QIN B071NFVVNG", notes:"第三方 Amazon 估算；不同关键词结果集会有估值漂移。", body:"# HAF-QIN 相邻月趋势代理\n\n2026-08 精确 OEM ASIN B071NFVVNG 估算月销量 50,000，环比 -16.7%，反推 2026-07 约 60,000。价格 $36.99，评分 4.7，评论约 43.4K。仅作同页相邻月方向代理。\n" },
  { id:"SRC-REF-031", file:"refrigerator-filter-31.md", url:"https://www.asinsight.com/report/US/xwfe-refrigerator-water-filter", title:"ASINSIGHT XWFE 相邻月趋势代理", sourceType:"market", entity:"XWFE B0882ZJ48W", notes:"第三方 Amazon 估算；不可与其他关键词页的数值拼接。", body:"# XWFE 相邻月趋势代理\n\n2026-07 精确 OEM ASIN B0882ZJ48W 估算月销量 90,000，环比 +50%，反推 2026-06 约 60,000。价格 $49.98，评分 4.5，评论约 41.4K。仅作同页相邻月方向代理。\n" },
  { id:"SRC-REF-032", file:"refrigerator-filter-32.md", url:"https://www.asinsight.com/report/US/lt1000p-water-filter", title:"ASINSIGHT LT1000P 相邻月趋势代理", sourceType:"market", entity:"LT1000P B074HLRXMP", notes:"第三方 Amazon 估算，不是官方订单。", body:"# LT1000P 相邻月趋势代理\n\n2026-07 精确 OEM ASIN B074HLRXMP 估算月销量 40,000，环比 +1.5%，反推 2026-06 约 39,400。公开趋势轴没有完整月度点值。仅作同页相邻月方向代理。\n" },
  { id:"SRC-REF-033", file:"refrigerator-filter-33.md", url:"https://www.homedepot.com/p/EveryDrop-Ice-and-Refrigerator-Water-Filter-1-EDR1RXD1/205738745", title:"Home Depot EDR1RXD1 商品页", sourceType:"competitor", entity:"EDR1RXD1 retail", notes:"采集时点零售价，地区与促销可能变化。", body:"# Home Depot EDR1RXD1\n\n公开索引价 $59.99/支；买 2+ 约 $53.99/支。页面显示约 5.1K 评论，不同动态入口出现 5,116–5,217，报告采用约数。\n" },
  { id:"SRC-REF-034", file:"refrigerator-filter-34.md", url:"https://www.walmart.com/c/kp/whirlpool-refrigerator-water-filter-edr1rxd1", title:"Walmart EDR1RXD1 价格集合页", sourceType:"competitor", entity:"EDR1RXD1 Walmart offers", notes:"集合页混有 OEM 与兼容品，逐条区分。", body:"# Walmart EDR1RXD1 集合页\n\nOEM Everydrop 条目约 $57/支。兼容品可见 $22.99/2 支、$30.99/3 支、$53.99/6 支等，约 $8.99–$11.50/支。集合页混有第三方卖家，不能把兼容品当 OEM。\n" },
  { id:"SRC-REF-035", file:"refrigerator-filter-35.md", url:"https://www.samsung.com/us/home-appliance-accessories/haf-qin-refrigerator-water-filter-sku-haf-qin-exp/", title:"Samsung HAF-QIN 美国官方商品页", sourceType:"competitor", entity:"HAF-QIN official price", notes:"促销价页面显示缺货，只是报价信号。", body:"# Samsung HAF-QIN 官方页\n\n页面显示 $29.99，原价 $49.99，但状态为 Out of stock。不可当作稳定可成交价格。\n" },
  { id:"SRC-REF-036", file:"refrigerator-filter-36.md", url:"https://www.walmart.com/ip/SAMSUNG-Genuine-HAF-QIN-Refrigerator-Water-Filter-DA29-17376B-1-Pack/505423651", title:"Walmart Samsung HAF-QIN OEM", sourceType:"competitor", entity:"HAF-QIN Walmart OEM", notes:"Marketplace 价格与卖家可能变化。", body:"# Walmart HAF-QIN OEM\n\n页面标称 Samsung Genuine HAF-QIN / DA97-17376B，采集价约 $32.79/支，原价 $49.99。另有不同卖家条目价格更高，不能合并为单一真值。\n" },
  { id:"SRC-REF-037", file:"refrigerator-filter-37.md", url:"https://www.homedepot.com/p/Samsung-Genuine-HAF-QINS-Water-Filter-for-Samsung-Refrigerators-HAF-QINS/302029386", title:"Home Depot Samsung HAF-QINS", sourceType:"competitor", entity:"HAF-QINS retail", notes:"零售 SKU 后缀与 HAF-QIN/EXP 不完全相同。", body:"# Home Depot HAF-QINS\n\n公开价 $36.19/支，买 2+ $32.57/支。该零售 SKU 写 HAF-QINS，报告中不与 HAF-QIN/EXP 的认证后缀混用。\n" },
  { id:"SRC-REF-038", file:"refrigerator-filter-38.md", url:"https://www.homedepot.com/p/LG-LT1000PC-Premium-Refrigerator-Water-Filter-for-LG-LT1000PC-6-Month-200-Gallon-Capacity-NSF42-NSF53-and-NSF401-LT1000PC/310861276", title:"Home Depot LG LT1000PC OEM", sourceType:"competitor", entity:"LT1000P family retail", notes:"LT1000PC 属于官方 LT1000P 型号族零售 SKU。", body:"# Home Depot LT1000PC\n\n采集价 $43.99/支，原价 $54.98。型号写 LT1000PC，属于 LT1000P 系列，但报告保留精确后缀。\n" },
  { id:"SRC-REF-039", file:"refrigerator-filter-39.md", url:"https://www.bestbuy.com/site/reviews/water-filter-for-select-samsung-refrigerators-white/11004069?page=5", title:"Best Buy HAF-QIN 用户评论", sourceType:"other", entity:"HAF-QIN VOC", notes:"部分评论披露促销或抽奖激励，可能抬高满意度。", body:"# HAF-QIN Best Buy VOC\n\n3,113 reviews，96% 推荐。正向集中在容易安装、水冰口感清爽、4–6 个月使用体验。部分评论存在促销/抽奖激励披露，不能与 Samsung 官网失败反馈直接平均。\n" },
  { id:"SRC-REF-040", file:"refrigerator-filter-40.md", url:"https://www.samsung.com/au/home-appliance-accessories/hafqinexp-haf-qin-exp/", title:"Samsung AU HAF-QIN 官方评论", sourceType:"other", entity:"HAF-QIN VOC counterevidence", notes:"品牌官网可能聚集售后失败用户。", body:"# Samsung AU HAF-QIN VOC\n\n3.4/5，279 reviews，65% 推荐。负向出现新滤芯卡扣尺寸不一致、无法密封、持续漏水、化学味、白色残留等；这是 HAF-QIN 结构性漏水风险的重要反证。\n" },
  { id:"SRC-REF-041", file:"refrigerator-filter-41.md", url:"https://www.walmart.com/reviews/product/11488800302", title:"Walmart XWFE 带芯片兼容品评论", sourceType:"other", entity:"XWFE compatible VOC", notes:"只代表该具体 Listing，不外推所有兼容品。", body:"# XWFE 带芯片兼容品 VOC\n\n4.7/5，375 ratings、173 written reviews。正向为价格、安装快、可正常识别；负向包括一包中个别失效、标线与说明不清。关键词中 RFID 被明确提及。\n" },
  { id:"SRC-REF-042", file:"refrigerator-filter-42.md", url:"https://products.geappliances.com/appliance/gea-support-search-content?contentId=000060638", title:"GE XWFE RFID 与漏水检测说明", sourceType:"competitor", entity:"XWFE RFID", notes:"用于解释芯片的官方用途，不否定用户对锁定与价格的抱怨。", body:"# GE XWFE RFID 说明\n\nGE 说明 XWFE 内置 RFID/Leak-Detecting Sensing Technology，可在检测到滤芯处漏水时关闭水阀。型号改版后的头部槽/突起与安装识别会造成用户困惑。XWFE 是机械接口与电子握手双适配。\n" },
  { id:"SRC-REF-043", file:"refrigerator-filter-43.md", url:"https://www.bestbuy.com/site/reviews/lt1000p-lt1000pc-water-filter-for-select-lg-refrigerators-white/12338913?page=5", title:"Best Buy LT1000P/LT1000PC 用户评论", sourceType:"other", entity:"LT1000P VOC", notes:"部分评论存在促销激励披露。", body:"# LT1000P Best Buy VOC\n\n2,375 reviews，95% 推荐。主题计数：安装方便 760、水质 719、性能 334；负面主题价格 102、味道 5。OEM VOC 在四型号中最稳定，但部分评论披露促销考虑。\n" },
  { id:"SRC-REF-044", file:"refrigerator-filter-44.md", url:"https://www.walmart.com/reviews/product/2243455370", title:"Walmart LT1000P Waterdrop 兼容品评论", sourceType:"other", entity:"LT1000P compatible VOC", notes:"仅代表该 Waterdrop Listing。", body:"# LT1000P 兼容品 VOC\n\n4.4/5，146 ratings、48 written reviews。正向为低价、口感与贴合可接受；负向有错货、不适配和漏水，包括同一买家连续两个滤芯漏水的反证。\n" },
  { id:"SRC-REF-045", file:"refrigerator-filter-45.md", url:"https://www.everydropwater.com/content/dam/business-unit/everydrop/en_us/pdf/updated_performance_sheets/w11392626.pdf", title:"EveryDrop EDR1RXD1 官方性能数据表", sourceType:"regulation", entity:"EDR1RXD1 certification PDS", notes:"品牌性能表需与官方目录组合使用。", body:"# EDR1RXD1 Performance Data Sheet\n\n系统型号 P8WB2L（EDR1RXD1B），替换滤芯包含 EDR1RXD1、EDR1RXD1B、WHR1RXD1、KAD1RXD1；声明经 NSF 按 42、53、401 测试认证，容量 200 gallons。\n" },
  { id:"SRC-REF-046", file:"refrigerator-filter-46.md", url:"https://info.nsf.org/Certified/dwtu/Listings.asp?TradeName=EDR1RXD1", title:"NSF EDR1RXD1 官方目录", sourceType:"regulation", entity:"EDR1RXD1 NSF listing", notes:"[Pb] 是铅含量评估标记，不直接等同独立 372 条目。", body:"# NSF EDR1RXD1 目录\n\n持证主体 Whirlpool Corporation。目录精确映射系统 P8WB2L / 替换件 EDR1RXD1，并命中 NSF/ANSI 42、53、401。目录标示截至 2026-06-20 有效。[Pb] 不改写为独立 372 certified。\n" },
  { id:"SRC-REF-047", file:"refrigerator-filter-47.md", url:"https://info.nsf.org/Certified/DWTU/Listings.asp?Company=C0560112&Standard=042", title:"NSF Samsung HAF-QIN 官方目录", sourceType:"regulation", entity:"HAF-QIN NSF listing", notes:"EXP 与 XME 后缀及零件号不可混用。", body:"# NSF HAF-QIN 目录\n\n持证主体 Samsung Electronics Co., Ltd.。DA97-08006C 的替换件字段包含 HAF-QIN/EXP、DA97-17376B；42、53、401 均有目录命中。HAF-QIN/XME / DA97-17376A 是另一映射，覆盖不同，不能混用。\n" },
  { id:"SRC-REF-048", file:"refrigerator-filter-48.md", url:"https://www.geapplianceparts.com/xwfe-water-filter.html", title:"GE XWFE 官方认证说明", sourceType:"regulation", entity:"XWFE certification statement", notes:"IAPMO 精确目录证书号尚未核出。", body:"# GE XWFE 认证边界\n\nGE 官方资料称 XWFE 由 IAPMO R&T 按 NSF/ANSI 42、53、401、P473 测试/认证。当前未取得包含 XWFE 精确型号的 IAPMO 当前目录页或证书号，因此标为品牌性能资料已确认、官方目录精确行待补。\n" },
  { id:"SRC-REF-049", file:"refrigerator-filter-49.md", url:"https://info.nsf.org/Certified/DWTU/Listings.asp?Company=C0257345", title:"NSF LG LT1000P 官方目录", sourceType:"regulation", entity:"LT1000P NSF listing", notes:"精确映射型号族与替换件。", body:"# NSF LT1000P 目录\n\n持证主体 LG Electronics Inc.。系统/型号 MDJ64844601，替换件字段包含 LT1000P、LT1000PC、LT1000PCS、ADQ747935；42、53、401 均命中，额定 200 gal、0.5 gpm。[Pb] 不改写为独立 372 条目。\n" },
];

const main = async () => {
  const [sources, claims, log, analysis] = await Promise.all([
    readFile(path.join(root,"sources.json"),"utf8").then(JSON.parse), readFile(path.join(root,"claims.json"),"utf8").then(JSON.parse),
    readFile(path.join(root,"search_log.json"),"utf8").then(JSON.parse), readFile(path.join(root,"commercial_analysis.json"),"utf8").then(JSON.parse),
  ]);
  await mkdir(path.join(root,"source_snapshots"),{recursive:true});
  for (const row of rows) {
    await writeFile(path.join(root,"source_snapshots",row.file),row.body,"utf8");
    const source={id:row.id,url:row.url,title:row.title,sourceType:row.sourceType,retrievedAt:at,targetEntity:row.entity,targetMarket:"US",accessMethod:"web-fetch",accessStatus:"accessible",evidenceStatus:"verified",snapshotPath:`source_snapshots/${row.file}`,contentHash:createHash("sha256").update(row.body).digest("hex"),notes:row.notes};
    const i=sources.findIndex((x:{id:string})=>x.id===row.id); if(i>=0)sources[i]=source;else sources.push(source);
  }
  const additions=[
    {id:"CLM-RF-014",sourceId:"SRC-REF-029",statement:"EDR1RXD1 的相邻月需求代理基本稳定。",evidence:"同一 ASIN/同一页面口径下，2026-07 估算 90K，环比 +1.5%，反推 6 月约 88.7K。",confidence:"Medium",category:"trend",targetScope:"market",notes:"第三方估算。"},
    {id:"CLM-RF-015",sourceId:"SRC-REF-030",statement:"HAF-QIN 的最新相邻月需求代理回落。",evidence:"2026-08 估算 50K，环比 -16.7%，反推 7 月约 60K。",confidence:"Medium",category:"trend",targetScope:"market",notes:"第三方估算。"},
    {id:"CLM-RF-016",sourceId:"SRC-REF-031",statement:"XWFE 的最新相邻月需求代理增长最强。",evidence:"2026-07 估算 90K，环比 +50%，反推 6 月约 60K。",confidence:"Medium",category:"trend",targetScope:"market",notes:"第三方估算。"},
    {id:"CLM-RF-017",sourceId:"SRC-REF-032",statement:"LT1000P 的相邻月需求代理基本稳定。",evidence:"2026-07 估算 40K，环比 +1.5%，反推 6 月约 39.4K。",confidence:"Medium",category:"trend",targetScope:"market",notes:"第三方估算。"},
    {id:"CLM-RF-018",sourceId:"SRC-REF-033",statement:"四型号 OEM 跨平台价格主要落在约 $30–$60/支，兼容品常以约 $7–$18/支或多件装竞争。",evidence:"EDR1RXD1、HAF-QIN、XWFE、LT1000P 的品牌官网、Amazon、Home Depot 与 Walmart 同日价格矩阵显示稳定的 OEM/兼容品分层。",confidence:"High",category:"competitor",targetScope:"competitor",notes:"价格为采集时点，库存和促销会变化。"},
    {id:"CLM-RF-019",sourceId:"SRC-REF-033",statement:"EDR1RXD1 的主要售后风险是错配、锁止困难、提前流量衰减和冲洗后异味。",evidence:"Home Depot 约 5.1K 评论信号与 Walmart/品牌评论共同支持；兼容品另有漏水、颗粒和认证疑虑。",confidence:"High",category:"customer",targetScope:"competitor"},
    {id:"CLM-RF-020",sourceId:"SRC-REF-040",statement:"HAF-QIN 在四型号中呈现最强的结构性漏水反证。",evidence:"Best Buy 高推荐率与 Samsung 官方评论中的卡扣尺寸差异、密封失败和严重漏水形成明显平台偏差。",confidence:"High",category:"customer",targetScope:"competitor"},
    {id:"CLM-RF-021",sourceId:"SRC-REF-041",statement:"XWFE 的核心进入门槛是机械接口与 RFID 电子握手双适配。",evidence:"GE 官方解释 RFID 漏水检测用途；兼容品评论同时出现识别成功与个别失效、说明不清。",confidence:"High",category:"customer",targetScope:"competitor"},
    {id:"CLM-RF-022",sourceId:"SRC-REF-043",statement:"LT1000P 的 OEM 用户体验最稳定，但兼容品仍存在错配和漏水尾部风险。",evidence:"Best Buy 2,375 reviews、95% 推荐，安装与水质主题突出；Walmart 兼容品样本记录错货与连续漏水反证。",confidence:"High",category:"customer",targetScope:"competitor"},
    {id:"CLM-RF-023",sourceId:"SRC-REF-046",statement:"EDR1RXD1 在 NSF 官方目录精确命中 42、53、401。",evidence:"持证主体 Whirlpool Corporation；系统 P8WB2L / 替换件 EDR1RXD1。",confidence:"High",category:"regulation",targetScope:"competitor"},
    {id:"CLM-RF-024",sourceId:"SRC-REF-047",statement:"HAF-QIN/EXP / DA97-17376B 在 NSF 官方目录精确命中 42、53、401。",evidence:"持证主体 Samsung Electronics；EXP 与 XME 后缀不可混用。",confidence:"High",category:"regulation",targetScope:"competitor"},
    {id:"CLM-RF-025",sourceId:"SRC-REF-048",statement:"XWFE 的 GE 官方资料声明 IAPMO R&T 按 42、53、401、P473 认证，但精确目录证书号仍待取得。",evidence:"GE 官方认证说明与性能资料明确标准；本轮未找到可审计的 XWFE 当前 IAPMO 目录行。",confidence:"Medium",category:"regulation",targetScope:"competitor"},
    {id:"CLM-RF-026",sourceId:"SRC-REF-049",statement:"LT1000P 型号族在 NSF 官方目录精确命中 42、53、401。",evidence:"持证主体 LG Electronics；MDJ64844601 的替换件包含 LT1000P/LT1000PC/LT1000PCS/ADQ747935。",confidence:"High",category:"regulation",targetScope:"competitor"},
  ];
  for(const c of additions){const i=claims.findIndex((x:{id:string})=>x.id===c.id);if(i>=0)claims[i]=c;else claims.push(c)}
  const qs=[
    {id:"Q-REF-012",query:"four refrigerator filter exact OEM ASIN adjacent-month trend proxies EDR1RXD1 HAF-QIN XWFE LT1000P",surface:"Exa Web Search + Fetch",executedAt:at,outcome:"yielded_sources",resultsFound:177,extractedCount:16,deduplicatedCount:16,validCount:16,keptSourceIds:["SRC-REF-029","SRC-REF-030","SRC-REF-031","SRC-REF-032"]},
    {id:"Q-REF-013",query:"four refrigerator filter cross-platform OEM and compatible price matrix",surface:"Exa Web Search + Fetch",executedAt:at,outcome:"yielded_sources",resultsFound:32,extractedCount:16,deduplicatedCount:15,validCount:12,keptSourceIds:["SRC-REF-033","SRC-REF-034","SRC-REF-035","SRC-REF-036","SRC-REF-037","SRC-REF-038","SRC-REF-024","SRC-REF-025","SRC-REF-005"]},
    {id:"Q-REF-014",query:"independent model-level VOC EDR1RXD1 HAF-QIN XWFE LT1000P OEM and compatible",surface:"Exa Web Search + Fetch",executedAt:at,outcome:"yielded_sources",resultsFound:105,extractedCount:24,deduplicatedCount:22,validCount:18,keptSourceIds:["SRC-REF-033","SRC-REF-039","SRC-REF-040","SRC-REF-041","SRC-REF-042","SRC-REF-043","SRC-REF-044"]},
    {id:"Q-REF-015",query:"official NSF IAPMO certification directory exact EDR1RXD1 HAF-QIN XWFE LT1000P",surface:"Exa Web Search + Official Directory Fetch",executedAt:at,outcome:"yielded_sources",resultsFound:145,extractedCount:12,deduplicatedCount:11,validCount:8,keptSourceIds:["SRC-REF-045","SRC-REF-046","SRC-REF-047","SRC-REF-048","SRC-REF-049"]},
  ];
  for(const q of qs){const i=log.queries.findIndex((x:{id:string})=>x.id===q.id);if(i>=0)log.queries[i]=q;else log.queries.push(q)} log.generatedAt=at;
  analysis.generatedAt=at;
  analysis.marketOpportunity.demand={score:86,rationale:"四个优先型号均取得同一精确 OEM ASIN、同一页面口径的相邻月需求代理：EDR1RXD1 与 LT1000P 基本稳定，HAF-QIN 最新月回落，XWFE 最新月增长最强；均为第三方估算而非官方订单。",sourceIds:["SRC-REF-029","SRC-REF-030","SRC-REF-031","SRC-REF-032"]};
  analysis.marketOpportunity.trend={score:78,rationale:"已形成四型号 2026 年相邻月份的月度趋势代理，不再停留在单月快照；公开页面仍未提供完整 12 个月逐月数值，因此只判断方向与量级。",sourceIds:["SRC-REF-029","SRC-REF-030","SRC-REF-031","SRC-REF-032"]};
  analysis.marketOpportunity.competition={score:90,rationale:"跨平台价格矩阵显示 OEM 约 $30–$60/支、兼容品常见约 $7–$18/支；价格差足够吸引替代，但 HAF-QIN 漏水、XWFE RFID 和各型号适配尾部风险构成实质进入门槛。",sourceIds:["SRC-REF-033","SRC-REF-034","SRC-REF-035","SRC-REF-036","SRC-REF-037","SRC-REF-038","SRC-REF-041","SRC-REF-042"]};
  analysis.marketOpportunity.monetization={score:78,rationale:"四型号已建立品牌官网、Amazon、Home Depot、Walmart 的同日价格矩阵，能识别 OEM 溢价、多件装和兼容品价格带；目标供应成本、履约与退货成本仍需 RFQ 闭环。",sourceIds:["SRC-REF-033","SRC-REF-034","SRC-REF-035","SRC-REF-036","SRC-REF-037","SRC-REF-038","SRC-REF-024","SRC-REF-025","SRC-REF-005"]};
  analysis.marketOpportunity.overall=79;
  analysis.marketOpportunity.verdict="四个型号均有持续需求信号，但不是同一种生意：EDR1RXD1 需求信号较强且售后敏感，HAF-QIN 漏水反证最强，XWFE 受 RFID 双适配约束，LT1000P OEM 体验最稳定、兼容替代窗口最清晰。当前仅有相邻月份的第三方趋势估算，尚不足以证明全年需求稳定；建议优先验证 LT1000P 与 EDR1RXD1，HAF-QIN 和 XWFE 提高样测门槛。";
  analysis.competitorInsight.pricePositioning="同日跨平台矩阵显示 OEM 大致 $30–$60/支，兼容品常以约 $7–$18/支或多件装成交。EDR1RXD1 OEM 约 $50.80–$59.99，HAF-QIN 约 $29.99–$37.89，XWFE 约 $49.02–$54.99，LT1000P 约 $43.99–$54.99；促销、库存和地区价格单独标注。";
  analysis.competitorInsight.reviews="型号级独立 VOC 已覆盖大型零售商、品牌官网和社区：EDR1RXD1 重点是错配/锁止/流量衰减；HAF-QIN 是尺寸与漏水；XWFE 是 RFID/ERR；LT1000P OEM 最稳定但兼容品仍有漏水尾部风险。";
  analysis.competitorInsight.socialProof="评论平台之间存在系统性偏差：Best Buy 高推荐率受促销评论影响，品牌官网更聚集失败用户；报告保留双口径和反证，不合并成虚假的平均满意度。";
  analysis.competitorInsight.sourceIds=[...new Set([...analysis.competitorInsight.sourceIds,...rows.filter(r=>r.sourceType==="competitor"||r.sourceType==="other").map(r=>r.id)])];
  analysis.customerInsight.painPoints=["EDR1RXD1：错配、锁止失败、提前流量衰减与冲洗后异味","HAF-QIN：卡扣尺寸差异、密封失败与严重漏水","XWFE：RFID/ERR、芯片识别与黑灰颗粒","LT1000P：OEM 高价，兼容品偶发错配与漏水","所有型号：认证与具体 SKU/后缀是否一致"];
  analysis.customerInsight.sourceIds=[...new Set([...analysis.customerInsight.sourceIds,"SRC-REF-033","SRC-REF-039","SRC-REF-040","SRC-REF-041","SRC-REF-042","SRC-REF-043","SRC-REF-044"] )];
  analysis.productDecision.rationale=["四型号均有相邻月需求代理与跨平台价格矩阵","型号级 VOC 已能区分不同测试重点，不能再用同一套通用漏水测试覆盖全部型号","EDR1RXD1、HAF-QIN、LT1000P 已在 NSF 目录精确命中；XWFE 仍需补 IAPMO 精确目录证书号","正式到岸成本和目标样品表现仍决定最终进入顺序"];
  analysis.productDecision.sourceIds=[...new Set([...analysis.productDecision.sourceIds,"SRC-REF-029","SRC-REF-030","SRC-REF-031","SRC-REF-032","SRC-REF-046","SRC-REF-047","SRC-REF-048","SRC-REF-049"] )];
  analysis.unknowns=["四型号完整 12 个月逐月趋势数值与真实转化率/退货率","XWFE 包含精确型号的当前 IAPMO 目录页或证书编号","目标供应商正式报价、包装、运费、关税与到岸成本","目标样品的型号公差、密封、流量、口感、RFID 与证书一致性"];
  await Promise.all([writeFile(path.join(root,"sources.json"),JSON.stringify(sources,null,2)+"\n"),writeFile(path.join(root,"claims.json"),JSON.stringify(claims,null,2)+"\n"),writeFile(path.join(root,"search_log.json"),JSON.stringify(log,null,2)+"\n"),writeFile(path.join(root,"commercial_analysis.json"),JSON.stringify(analysis,null,2)+"\n")]);
  console.log(JSON.stringify({sources:sources.length,claims:claims.length,queries:log.queries.length},null,2));
};
main().catch(e=>{console.error(e);process.exit(1)});
